### ISSUE TITLE
Nimbus Documentation for connected peers out of sync

### ISSUE THREAD

**Issue by jcomfort4** [SomerEsat/ethereum-staking-guide#2]
The current documentation for checking connected peers says to run the following command..

![image](https://user-images.githubusercontent.com/8152811/108638331-bf495700-745c-11eb-9e8c-3455905aa5f6.png)

However, for Nimbus, we don't open the http connection and this actually should be `geth attach ws://127.0.0.1:8546` -- notice that the `ws://` instead of `http://` and then `8546` instead of `8545`

**Comment by SomerEsat** [comment]
@jcomfort4 not sure where you're looking?

The [current mainnet guide](https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-nimbus-e86bdee8c550) has the correct endpoint.

![image](https://user-images.githubusercontent.com/60827187/108638728-7afe8c80-7445-11eb-8407-e770e58faf78.png)

**Comment by SomerEsat** [comment]
Oh wait... I see it now. Sorry. Yes. I'll fix that. Thanks for the find.

**Comment by SomerEsat** [comment]
Fixed
